/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class srmp_SRMPJni */

#ifndef _Included_srmp_SRMPJni
#define _Included_srmp_SRMPJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     srmp_SRMPJni
 * Method:    Options
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_srmp_SRMPJni_Options
  (JNIEnv *, jclass);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1Dispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetMethod
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetMethod
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_srmp_SRMPJni_Options_1GetMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetMaxIterations
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetMaxIterations
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetMaxIterations
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_srmp_SRMPJni_Options_1GetMaxIterations
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetMaxTime
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetMaxTime
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetMaxTime
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_srmp_SRMPJni_Options_1GetMaxTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetEPS
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetEPS
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetEPS
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_srmp_SRMPJni_Options_1GetEPS
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetComputeSolutionPeriod
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetComputeSolutionPeriod
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetComputeSolutionPeriod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_srmp_SRMPJni_Options_1GetComputeSolutionPeriod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetPrintTimes
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetPrintTimes
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetPrintTimes
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_srmp_SRMPJni_Options_1GetPrintTimes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetSortFlag
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetSortFlag
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetSortFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_srmp_SRMPJni_Options_1GetSortFlag
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetIsVerbose
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetIsVerbose
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetIsVerbose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_srmp_SRMPJni_Options_1GetIsVerbose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_SetTRWSWeighting
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Options_1SetTRWSWeighting
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     srmp_SRMPJni
 * Method:    Options_GetTRWSWeighting
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_srmp_SRMPJni_Options_1GetTRWSWeighting
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_srmp_SRMPJni_Energy
  (JNIEnv *, jclass, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Energy_1Dispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_AddNode
 * Signature: (JI[D)I
 */
JNIEXPORT jint JNICALL Java_srmp_SRMPJni_Energy_1AddNode
  (JNIEnv *, jclass, jlong, jint, jdoubleArray);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_AddUnaryFactor
 * Signature: (JI[D)J
 */
JNIEXPORT jlong JNICALL Java_srmp_SRMPJni_Energy_1AddUnaryFactor
  (JNIEnv *, jclass, jlong, jint, jdoubleArray);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_AddPairwiseFactor
 * Signature: (JII[D)J
 */
JNIEXPORT jlong JNICALL Java_srmp_SRMPJni_Energy_1AddPairwiseFactor
  (JNIEnv *, jclass, jlong, jint, jint, jdoubleArray);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_AddFactor
 * Signature: (JI[I[DI)J
 */
JNIEXPORT jlong JNICALL Java_srmp_SRMPJni_Energy_1AddFactor
  (JNIEnv *, jclass, jlong, jint, jintArray, jdoubleArray, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_GetNodeNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_srmp_SRMPJni_Energy_1GetNodeNum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_GetK
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_srmp_SRMPJni_Energy_1GetK
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_Solve
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_srmp_SRMPJni_Energy_1Solve
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_GetSolution
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_srmp_SRMPJni_Energy_1GetSolution
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_SetMinimalEdges
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Energy_1SetMinimalEdges
  (JNIEnv *, jclass, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_SetFullEdges
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Energy_1SetFullEdges
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_SetFullEdgesDual
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Energy_1SetFullEdgesDual
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_AddRelaxationEdge
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Energy_1AddRelaxationEdge
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_IsSuperset
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_srmp_SRMPJni_Energy_1IsSuperset
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_AddTriplet
 * Signature: (JIIIZ)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Energy_1AddTriplet
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_SaveUAI
 * Signature: (JLjava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Energy_1SaveUAI
  (JNIEnv *, jclass, jlong, jstring, jboolean, jboolean);

/*
 * Class:     srmp_SRMPJni
 * Method:    Energy_PrintStats
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_srmp_SRMPJni_Energy_1PrintStats
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
